version: '3'
services:
  product-core-service:
    image: jadecoma/product-core-service
    container_name: product-core-service
    depends_on:
      - eureka-server
#    ports:
#      - "9000:9000"
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    external_links:
      - mysql-product-service:mysql


  customer-core-service:
    image: jadecoma/customer-core-service
    container_name: customer-core-service
    depends_on:
      - eureka-server
    ports:
      - "9010:9010"
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    external_links:
      - mysql-customer-service:mysql


  category-core-service:
    image: jadecoma/category-core-service
    container_name: category-core-service
    depends_on:
      - eureka-server
#    ports:
#      - "9020:9020"
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    external_links:
      - mysql-category-service:mysql


  user-composite-service:
    image: jadecoma/user-composite-service
    container_name: user-composite-service
    depends_on:
      - eureka-server
    external_links:
      - customer-core-service
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    ports:
      - "9100:9100"


  product-composite-service:
    image: jadecoma/product-composite-service
    container_name: product-composite-service
    depends_on:
      - eureka-server
    external_links:
      - product-core-service
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
#    ports:
#      - "9200:9200"


  portfolio-composite-service:
    image: jadecoma/portfolio-composite-service
    container_name: portfolio-composite-service
    depends_on:
      - eureka-server
    external_links:
      - product-core-service
      - category-core-service
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
#    ports:
#      - "9300:9300"


  db-products:
    image: mysql:5.6
    container_name: mysql-product-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-product
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass


  db-customers:
    image: mysql:5.6
    container_name: mysql-customer-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-customer
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass


  db-categories:
    image: mysql:5.6
    container_name: mysql-category-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-category
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass


  eureka-server:
    image: jadecoma/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"


  zuul:
    image: jadecoma/zuul
    container_name: zuul
    depends_on:
      - eureka-server
    ports:
      - "9090:9090"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    container_name: start_dependencies
    depends_on:
      - eureka-server
    command: eureka-server:8761