version: '3'
services:
  oauth-server:
    image: jadecoma/oauth-server
    container_name: oauth-server
    ports:
      - "8081:8081"
    external_links:
      - db-oauth:mysql

  product-core-service:
    image: jadecoma/product-core-service
    container_name: product-core-service
    depends_on:
      - eureka-server
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    external_links:
      - mysql-product-service:mysql


  customer-core-service:
    image: jadecoma/customer-core-service
    container_name: customer-core-service
    depends_on:
      - eureka-server
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    external_links:
      - mysql-customer-service:mysql


  category-core-service:
    image: jadecoma/category-core-service
    container_name: category-core-service
    depends_on:
      - eureka-server
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "
    external_links:
      - mysql-category-service:mysql


  user-composite-service:
    image: jadecoma/user-composite-service
    container_name: user-composite-service
    depends_on:
      - eureka-server
    external_links:
      - customer-core-service
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "

  product-composite-service:
    image: jadecoma/product-composite-service
    container_name: product-composite-service
    depends_on:
      - eureka-server
    external_links:
      - product-core-service
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "


  portfolio-composite-service:
    image: jadecoma/portfolio-composite-service
    container_name: portfolio-composite-service
    depends_on:
      - eureka-server
    external_links:
      - product-core-service
      - category-core-service
    command: >
      /bin/bash -c "
      nc -z eureka-server 8761 &&
      echo Connected to EUREKA and started!
      "


  db-products:
    image: mysql:5.6
    container_name: mysql-product-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-product
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass



  db-customers:
    image: mysql:5.6
    container_name: mysql-customer-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-customer
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass


  db-categories:
    image: mysql:5.6
    container_name: mysql-category-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-category
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass


  db-oauth:
    image: mysql:5.6
    container_name: mysql-oauth-service
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vis-shop-oauth
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pass


  web-shop-db-image:
    image: mavogel/hska-vis-web-shop-db-image
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"

  legacywebshop:
    image: mavogel/hska-vis-legacywebshop
    depends_on:
      - web-shop-db-image
      - zuul
      - product-composite-service
      - product-core-service
      - oauth-server
    links:
      - web-shop-db-image
      - zuul
      - product-composite-service
      - product-core-service
      - oauth-server
    ports:
      - "8888:8080"


  eureka-server:
    image: jadecoma/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"


  zuul:
    image: jadecoma/zuul
    container_name: zuul
    depends_on:
      - eureka-server
    external_links:
      - oauth-server
    links:
      - oauth-server
    ports:
      - "9090:9090"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    container_name: start_dependencies
    depends_on:
      - eureka-server
    command: eureka-server:8761