server:
  port: ${server_port:9020}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

spring:
  application:
    name: category-core-service
  devtools:
    remote:
      secret: mysecret
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://mysql:3306/vis-shop-category
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver

management:
  security:
    enabled: false