server:
  port: ${server_port:9200}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

spring:
  application:
    name: product-composite-service
  devtools:
    remote:
      secret: mysecret

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream