server:
  port: ${server_port:9090}


eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}


zuul:
  prefix: /api
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'

  routes:
    products:
      path: /products/**
      url: http://product-core-service:9000
    customers:
      path: /customers/**
      url: http://customer-core-service:9001
    categories:
      path: /categories/**
      url: http://category-core-service:9002

spring:
  application:
    name: zuul-server

management:
  security:
    enabled: false