server:
  port: ${server_port:9090}


eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}


zuul:
  prefix: /api
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'

  routes:
    portfolio:
      path: /portfolio/**
      url: http://portfolio-composite-service:9300
    products:
      path: /products/**
      url: http://product-composite-service:9200
    customers:
      path: /customers/**
      url: http://user-composite-service:9100
    uaa:
      path: /login/**
      sensitiveHeaders:
      serviceId: oauth-server

spring:
  application:
    name: zuul-server

management:
  security:
    enabled: false

security:
  oauth2:
    resource:
      user-info-uri: http://oauth-server:8081/auth/user