server:
  port: ${server_port:9010}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
    instanceId: "${spring.application.name}:${random.value}"
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

spring:
  application:
    name: customer-core-service
  devtools:
    remote:
      secret: mysecret
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://mysql:3306/vis-shop-customer
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver

management:
  security:
    enabled: false