server:
  port: ${server_port:9300}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}

spring:
  application:
    name: portfolio-composite-service
  devtools:
    remote:
      secret: mysecret

management:
  security:
    enabled: false