server:
  port: ${server_port:9050}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
    instanceId: "${spring.application.name}:${random.value}"
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://eureka-server:8761/eureka/}
#    healthcheck:
#      enabled: true
#    lease:
#      duration: 5

spring:
  application:
    name: user-composite-service
  devtools:
    remote:
      secret: mysecret

management:
  security:
    enabled: false